# Generated by Django 3.2.4 on 2021-07-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='is_collector',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='is_donor',
            field=models.BooleanField(default=False),
        ),
    ]
