# Generated by Django 3.2.4 on 2021-07-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuprequest',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
